### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by iwensu0313** [iwensu0313/ca-aquaculture#1]
- [ ] Add in 2018 Census data for food fish and molluscs
- [ ] Fix url link to us-aquaculture dashboard
- [ ] Add a totals line from imports, adding up sales for all countries for a given product
